---
- name: Configure OSPF on R1
  gather_facts: False
  hosts: R1
  connection: network_cli

  tasks:
    - name: R1
      ios_config:
        lines:
          - network 1.1.1.1 0.0.0.0 area 0
          - network 10.2.2.0 0.0.0.3 area 0
          - network 10.3.3.0 0.0.0.3 area 0
          - router-id 1.1.1.1
        parents: ['router ospf 1']        


- name: Configure OSPF on R2
  gather_facts: False
  hosts: R2
  connection: network_cli

  tasks:
    - name: R2
      ios_config:
        lines:
          - network 2.2.2.2 0.0.0.0 area 0
          - network 10.2.2.0 0.0.0.3 area 0
          - router-id 2.2.2.2
        parents: ['router ospf 1'] 


- name: Configure OSPF on R3
  gather_facts: False
  hosts: R3
  connection: network_cli

  tasks:
    - name: R3
      ios_config:
        lines:
          - network 3.3.3.3 0.0.0.0 area 0
          - network 10.3.3.0 0.0.0.3 area 0
          - router-id 3.3.3.3
        parents: ['router ospf 1'] 


- name: Configure SNMP and NTP on all routers
  gather_facts: False
  hosts: routers
  connection: network_cli

  tasks:
    - name: Configure SNMP and NTP
      ios_config:
        lines:
          - snmp-server community tepa ro
          - snmp-server enable traps tty
          - ntp server 8.8.8.8
          - ntp server 4.2.2.2

