---
- name: "Task : Configure OSPF on Cisco IOS Routers"
  gather_facts: False
  hosts: R1
  connection: network_cli

  tasks:
    - name: Configure OSPF
      cisco.ios.ios_ospfv2:
        config:
          processes:
          - process_id: 1
            areas:
            - area_id: '0'
            network:
            - address: 1.1.1.1
            - wildcard_bits: 0.0.0.0
            - area: 0
            - address: 10.2.2.0
            - wildcard_bits: 0.0.0.3
            - area: 0
            - address: 10.3.3.0
            - wildcard_bits: 0.0.0.3
            - area: 0
      register: config_output

    - name: Display at console
      debug: var=config_output

