---
- name: Configure OSPF on Cisco IOS Routers
  gather_facts: False
  hosts: R2
  connection: network_cli

  tasks:
    - name: Configure OSPF
      ios_config:
        lines:
          - router ospf 1
          - network 2.2.2.2 0.0.0.0
          - network 10.2.2.0 0.0.0.3
          - router-id 2.2.2.2

      register: config_output

    - name: Display at console
      debug: var=config_output